### ISSUE TITLE
Dexcom plugin

### ISSUE THREAD

**Issue by many7695** [huttotw/homebridge-dexcom#1]
Dexcom plugin 0.1.0 the rest of Homebridge is up to date using windows 10, with your plugin enabled my Homebridge stops running and when I disable the plugin my server starts running again. ( Homebridge server seems to run for a second before it stops running)

**Comment by huttotw** [comment]
@many7695 do you have any logs you can share?

**Comment by many7695** [comment]
[2023-04-12, 3:50:34 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:50:35 p.m.] [Homebridge UI] Homebridge log truncated by many7695.
[2023-04-12, 3:50:36 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:50:38 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:50:44 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:50:46 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:50:48 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:50:54 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:50:56 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:50:58 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:51:04 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:51:06 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:51:08 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:51:14 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:51:16 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:51:18 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:51:24 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:51:26 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:51:28 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:51:34 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:51:36 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:51:38 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:51:44 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:51:46 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:51:48 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:51:54 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:51:57 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:51:59 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:52:04 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:52:07 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:52:09 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:52:15 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:52:17 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:52:19 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:52:25 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:52:27 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:52:29 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:52:34 p.m.] [Homebridge UI] Changes to config.json saved.
[2023-04-12, 3:52:35 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:52:37 p.m.] [Smartglass] Xbox found on the network: 192.168.2.38
[2023-04-12, 3:52:39 p.m.] [Smartglass] Failed to connect to xbox. Reason: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.2.38'
}
[2023-04-12, 3:52:40 p.m.] [Homebridge UI] Changes to config.json saved.
[2023-04-12, 3:52:45 p.m.] [Smartglass] Device status: Disconnected
[2023-04-12, 3:52:45 p.m.] [Homebridge UI] Homebridge restart request received
[2023-04-12, 3:52:45 p.m.] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[2023-04-12, 3:52:45 p.m.] [Homebridge UI] Sending SIGTERM to Homebridge
[2023-04-12, 3:52:45 p.m.] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTERM
[2023-04-12, 3:52:50 p.m.] [HB Supervisor] Restarting Homebridge...
[2023-04-12, 3:52:50 p.m.] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[2023-04-12, 3:52:50 p.m.] [HB Supervisor] Started Homebridge v1.6.0 with PID: 12976
[2023-04-12, 3:52:51 p.m.] Loaded config.json with 0 accessories and 5 platforms.
[2023-04-12, 3:52:51 p.m.] Loaded 10 cached accessories from cachedAccessories.
[2023-04-12, 3:52:51 p.m.] ---
[2023-04-12, 3:52:52 p.m.] Loaded plugin: homebridge-config-ui-x@4.50.2
[2023-04-12, 3:52:52 p.m.] Registering platform 'homebridge-config-ui-x.config'
[2023-04-12, 3:52:52 p.m.] ---
[2023-04-12, 3:52:52 p.m.] Loaded plugin: homebridge-dexcom@0.1.0
[2023-04-12, 3:52:52 p.m.] Registering platform 'homebridge-dexcom.Dexcom'
[2023-04-12, 3:52:52 p.m.] ---
[2023-04-12, 3:52:52 p.m.] Loaded plugin: homebridge-nest@4.6.9
[2023-04-12, 3:52:52 p.m.] Registering platform 'homebridge-nest.Nest'
[2023-04-12, 3:52:52 p.m.] ---
[2023-04-12, 3:52:52 p.m.] Loaded plugin: homebridge-smartglass@1.0.4
[2023-04-12, 3:52:52 p.m.] Registering platform 'homebridge-smartglass.Smartglass'
[2023-04-12, 3:52:52 p.m.] ---
[2023-04-12, 3:52:53 p.m.] Loaded plugin: @milo526/homebridge-tuya-web@1.1.3
[2023-04-12, 3:52:53 p.m.] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'
[2023-04-12, 3:52:53 p.m.] ---
[2023-04-12, 3:52:53 p.m.] Loading 5 platforms...
[2023-04-12, 3:52:53 p.m.] [Smartglass] Initializing Smartglass platform...
[2023-04-12, 3:52:53 p.m.] [Smartglass] Finished initializing platform: Smartglass
[2023-04-12, 3:52:53 p.m.] [Nest] Initializing Nest platform...
[2023-04-12, 3:52:53 p.m.] [smartlife] Initializing TuyaWebPlatform platform...
[2023-04-12, 3:52:53 p.m.] [smartlife] Finished initializing platform: smartlife
[2023-04-12, 3:52:53 p.m.] [Dexcom] Initializing Dexcom platform...
[2023-04-12, 3:52:53 p.m.] [Dexcom] Initialized Dexcom client
[2023-04-12, 3:52:53 p.m.] [Dexcom] Finished initializing platform: undefined
[2023-04-12, 3:52:53 p.m.] [smartlife] Loading accessory from cache: Kitchen Light
[2023-04-12, 3:52:53 p.m.] [smartlife] Loading accessory from cache: Kitchen Light
[2023-04-12, 3:52:53 p.m.] [smartlife] Loading accessory from cache: Kitchen light
[2023-04-12, 3:52:53 p.m.] [smartlife] Loading accessory from cache: Moon Light On
[2023-04-12, 3:52:53 p.m.] [smartlife] Loading accessory from cache: Moon Light Off
[2023-04-12, 3:52:53 p.m.] [Smartglass] Executed didFinishLaunching callback
[2023-04-12, 3:52:53 p.m.] [Smartglass] Adding new accessory: XBOX
[2023-04-12, 3:52:53 p.m.] [Smartglass] Checking Xbox api capabilities...
[2023-04-12, 3:52:53 p.m.] [Nest] Fetching Nest devices.
[2023-04-12, 3:52:53 p.m.] [Nest] Authenticating via Google.
[2023-04-12, 3:52:53 p.m.] [smartlife] Requesting new token
[2023-04-12, 3:52:53 p.m.] [Dexcom] Executed didFinishLaunching callback
[2023-04-12, 3:52:53 p.m.] [Dexcom] Adding new device: Dexcom
[2023-04-12, 3:52:53 p.m.] [Dexcom] Added service Dexcom
[2023-04-12, 3:52:53 p.m.] Publishing external accessory (name: XBOX, publishInfo: {
  username: '70:B7:4A:81:29:5A',
  pincode: '***-**-***',
  category: 35,
  port: undefined,
  bind: [ 'Wi-Fi', [length]: 1 ],
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: undefined
}).
[2023-04-12, 3:52:53 p.m.] Publishing bridge accessory (name: Homebridge B925, publishInfo: {
  username: '0E:43:62:06:81:9A',
  port: 51575,
  pincode: '***-**-***',
  category: 2,
  bind: [ 'Wi-Fi', [length]: 1 ],
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: undefined
}).
Setup Payload:
X-HM://0023PYH5N34ES
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 151-59-387 │     
    └────────────┘     
                       
[2023-04-12, 3:52:53 p.m.] [Smartglass] User is authenticated with the Xbox api. Enabling functionalities
[2023-04-12, 3:52:53 p.m.] XBOX F570 is running on port 51946.
[2023-04-12, 3:52:53 p.m.] Please add [XBOX F570] manually in Home app. Setup Code: 151-59-387
[2023-04-12, 3:52:53 p.m.] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge B925) is running on port 51575.
[2023-04-12, 3:52:53 p.m.] [Smartglass] Get xbox console type from Xbox API: XboxSeriesS
[2023-04-12, 3:52:54 p.m.] AxiosError: Request failed with status code 500
    at settle (C:\Users\eeste\AppData\Roaming\npm\node_modules\homebridge-dexcom\node_modules\axios\lib\core\settle.js:19:12)
    at IncomingMessage.handleStreamEnd (C:\Users\eeste\AppData\Roaming\npm\node_modules\homebridge-dexcom\node_modules\axios\lib\adapters\http.js:556:11)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2023-04-12, 3:52:54 p.m.] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[2023-04-12, 3:52:59 p.m.] [HB Supervisor] Restarting Homebridge...
[2023-04-12, 3:52:59 p.m.] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[2023-04-12, 3:52:59 p.m.] [HB Supervisor] Started Homebridge v1.6.0 with PID: 8268
[2023-04-12, 3:53:00 p.m.] Loaded config.json with 0 accessories and 5 platforms.
[2023-04-12, 3:53:00 p.m.] Loaded 11 cached accessories from cachedAccessories.
[2023-04-12, 3:53:00 p.m.] ---
[2023-04-12, 3:53:00 p.m.] Loaded plugin: homebridge-config-ui-x@4.50.2
[2023-04-12, 3:53:00 p.m.] Registering platform 'homebridge-config-ui-x.config'
[2023-04-12, 3:53:00 p.m.] ---
[2023-04-12, 3:53:01 p.m.] Loaded plugin: homebridge-dexcom@0.1.0
[2023-04-12, 3:53:01 p.m.] Registering platform 'homebridge-dexcom.Dexcom'
[2023-04-12, 3:53:01 p.m.] ---

**Comment by huttotw** [comment]
@many7695 were you able to figure it out? If so, what was the issue?

As far as the logs, there's not a ton to go off of. I have published version 0.1.1 that adds some more error logging for requests. Could you try upgrading and sharing the logs again?

My hunch is that something in your configuration file is wrong. Are you sure that the `applicationId` is set to `d89443d2-327c-4a6f-89e5-496bbb0317db`? That is a constant value required for the API calls to work.

**Comment by many7695** [comment]
![IMG_0411](https://user-images.githubusercontent.com/3122959/231918534-b2d7a0d8-9afe-4726-a069-2ce5ad73e6f4.jpeg)

I’m thinking the issue might be because I’m in Canada
